getwd()
list.files()
setwd("D:/dsr")
getwd()
list.files()
data<-read.csv("Churn_Modelling.csv.xlsx")
data
colnames(data)
data$EstimatedSalary
income_group<-vector(mode="character",length=length(data$EstimatedSalary))
income_group
income_group[data$EstimatedSalary<10000]<-"Low"
income_group[data$EstimatedSalary>=10000 & data$EstimatedSalary < 100000]<-"middle"
income_group[data$EstimatedSalary>100000]<-"High"
income_group
spending_level<-factor(income_group,levels=c("Low","middle","High"),ordered=TRUE)
spending_level
data<-cbind(data,spending_level)
data
write.csv(data,"C:/Users/admin/Desktop/newData.csv",row.names=TRUE)